W4D5/music_app/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:new, :create, :show]

  resource :session, only: [:new, :create, :destroy]

  resources :bands do
    resources :albums, only: [:new]
  end

  resources :albums, except: [:index, :new] do
    resources :tracks, only: [:new]
  end

  resources :tracks, except: [:index, :new] do
    resources :notes, only: [:create, :destroy]
  end

end

W4D5/music_app/app/models/note.rb
class Note < ApplicationRecord
  validates :text, :track_id, :user_id, presence: true
  belongs_to :track
  belongs_to :user
end

W4D5/music_app/app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :require_logged_in

  def create
    note = Note.new(note_params)
    note.track_id = params[:track_id]
    note.user_id = current_user.id
    note.save
    redirect_to track_url(params[:track_id])
  end

  def destroy
    note = Note.find_by(id: params[:id])
    if note.user_id == current_user.id
      note.destroy
      redirect_to track_url(params[:track_id])
    else
      render text: 'You do not have permission to delete that note',
        status: 403
    end
  end

  private

  def note_params
    params.require(:note).permit(:text)
  end
end

W4D5/music_app/app/helpers/notes_helper.rb
module NotesHelper
end

W4D5/music_app/app/views/notes/_form.html.erb
<form class="form" action="<%= track_notes_url(track_id) %>" method="post">
  <%= auth_token %>
  <p>
    <label for="note-text">Content</label>
    <textarea id="note-text" name="note[text]" rows="10" cols="40"
    ></textarea>
  </p>
  <input type="submit">
</form>

W4D5/music_app/app/views/notes/_note.html.erb
<% unless notes.empty? %>
  <ul class="note-item">
    <% notes.each do |note| %>
      <li>
        <p><%= h(note.text) %></p>

        <div class="note-nav">
        <p>Authored by: <%= note.user.email %></p>

        <% if current_user.id == note.user_id %>
        <form action="<%= track_note_url(note.track_id, note.id) %>" method="post">
          <input type="hidden" name="_method" value="delete">
          <%= auth_token %>
          <input type="submit" value="Destroy Note">
        </form>
        <% end %>
        </div>
      </li>
    <% end %>
  </ul>
<% end %>