W5D2/reddit/config/routes.rb
Rails.application.routes.draw do
  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create]
  resources :subs, except: [:destroy]
  resources :posts, except: [:index, :destroy] do
    resources :comments, only: [:new]
    resources :votes, only: [:create]
  end
  resources :comments, only: [:create, :show]

end

W5D2/reddit/app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  title      :string           not null
#  url        :string
#  content    :text
#  author_id  :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Post < ApplicationRecord
  validates :title, presence: true

  has_many :post_subs, dependent: :destroy, inverse_of: :post
  has_many :subs, through: :post_subs

  has_many :comments
  belongs_to :author, class_name: :User

  has_many :votes, as: :votable
end

W5D2/reddit/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_logged_in, except: [:show]

  def new
    @post = Post.new
    render :new
  end

  def create
    @post = Post.new(post_params)
    @post.author_id = current_user.id
    if @post.save
      redirect_to post_url(@post.id)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :new
    end
  end

  def show
    @post = Post.find_by(id: params[:id])
    @comments_by_parent_id = comments_by_parent_id(@post)
    if @post
      render :show
    else
      redirect_to posts_url
    end
  end

  def comments_by_parent_id(post)
    hash = Hash.new { |h, k| h[k] = [] }
    post.comments.includes(:author).each do |comment|
      hash[comment.parent_comment_id] << comment
    end
    hash
  end

  def edit
    @post = Post.find_by(id: params[:id])
    if @post
      render :edit
    else
      redirect_to posts_url
    end
  end

  def update
    @post = Post.find_by(id: params[:id])
    if @post.update(post_params)
      render :show
    else
      flash.now[:errors] = @post.errors.full_messages
      render :edit
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :url, :content, sub_ids: [])
  end
end

W5D2/reddit/app/helpers/posts_helper.rb
module PostsHelper
end

W5D2/reddit/app/views/posts/_form.html.erb
<% action_url = action == :new ? posts_url : post_url(post.id) %>

<form class="form" action="<%= action_url %>" method="post">
  <% if action == :edit %>
    <input type="hidden" name="_method" value="patch">
  <% end %>
  <%= auth_token %>

  <label>Title:
    <input type="text" name="post[title]" value="<%= post.title %>">
  </label>
  <br>

  <label>URL:
    <input type="text" name="post[url]" value="<%= post.url %>">
  </label>
  <br>

  <label>Content:
    <textarea name="post[content]" rows="2" cols="20"
      ><%= post.content %></textarea>
  </label>
  <br>

  <input type="hidden" name="post[sub_ids][]" value="">
  <% Sub.all.each do |sub| %>
    <label>
    <input type="checkbox" name="post[sub_ids][]" value="<%= sub.id %>">
    <%= sub.title %></label>
    <br>
  <% end %>

  <input type="submit">
</form>

W5D2/reddit/app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

W5D2/reddit/app/views/posts/edit.html.erb
<h1>Edit Post!</h1>

<%= render 'form', action: :edit, post: @post %>

W5D2/reddit/app/views/posts/new.html.erb
<h1>New Post!</h1>

<%= render 'form', action: :new, post: @post %>

W5D2/reddit/app/views/posts/old_show_code.html.erb
<% unless @post.comments.empty? %>
  <ul>
    <% @post.comments.where(parent_comment_id: nil).each do |comment| %>
      <li><a href="<%= comment_url(comment.id) %>"><%= comment.content %></a>
      </li>
      <% unless comment.child_comments.empty? %>
        <%= render 'comments/comment', child_comments: comment.child_comments %>
      <% end %>
    <% end %>
  </ul>
<% else %>
  <br>
<% end %>

W5D2/reddit/app/views/posts/old_show_code_2.html.erb
<ul>
  <% @all_comments.where(parent_comment_id: nil).each do |comment| %>
    <li><a href="<%= comment_url(comment.id) %>"><%= comment.content %></a>
    </li>
    <% @all_comments.where(parent_comment_id: comment.id).each do |child| %>
      <%= render 'comments/comment', comment: child %>
    <% end %>
  <% end %>
</ul>

W5D2/reddit/app/views/posts/show.html.erb
<h1><a href="<%= @post.url %>"><%= @post.title %>
</a> by <%= @post.author.username %>
</h1>

<p>Content:<br><br>
  <%= @post.content %>
</p>

<%= button_to "Upvote", votes_url %>

<h4>Subs</h4>
<ul>
  <% unless @post.subs.empty? %>
    <% @post.subs.each do |sub| %>
      <li><a href="<%= sub_url(sub.id) %>"><%= sub.title %></a></li>
    <% end %>
  <% end %>
</ul>

<h1>Comments</h1>

<a href="<%= new_post_comment_url(@post.id) %>">Comment on this post!</a>

<% if @comments_by_parent_id[nil].empty? %>
  <br>
<% else %>
  <% @comments_by_parent_id[nil].each do |comment| %>
    <%= render 'comments/comment', comment: comment %>
  <% end %>
<% end %>


<% if current_user == @post.author %>
  <a href="<%= edit_post_url(@post.id) %>">Edit</a>
<% end %>

W5D2/reddit/app/views/posts/update.html.erb
<h1>Posts#update</h1>
<p>Find me in app/views/posts/update.html.erb</p>