W4D2/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :cats do
    resources :cat_rental_requests, only: [:index]
  end
  resources :cat_rental_requests
end

W4D2/app/models/cat.rb
class Cat < ApplicationRecord

COLORS = %w[black white brown green blue red orange yellow purple]
SEX = ["M", "F"]

validates :birth_date, :name, :sex, presence: true
validates :color, inclusion: { in: COLORS, message: "cats can't be that color!"}
validates :sex, inclusion: { in: SEX, message: "There's only two sexes!"}

has_many :cat_rental_requests,
primary_key: :id,
foreign_key: :cat_id,
class_name: :CatRentalRequest,
dependent: :destroy

def age
  d = Date.today
  birth = self.birth_date

  age = d.year - birth.year

  d_mo = d.month
  b_mo = birth.month

  age -=1 if d_mo < b_mo || d_mo == b_mo && d.day < b.day
end

def colors
  COLORS
end

def sexes
  SEX
end

end

W4D2/app/models/cat_rental_request.rb
class CatRentalRequest < ApplicationRecord
STATUSES = %w[APPROVED PENDING DENIED]

validates :status, inclusion: { in: STATUSES, message: "Invalid Status"}
validates :cat_id, :start_date, :end_date, presence: true
validate :does_not_overlap_approved_request

belongs_to :cat,
  primary_key: :id,
  foreign_key: :cat_id,
  class_name: :Cat


def overlapping_requests
  CatRentalRequest.joins(:cat)
    .where(cats: {id: cat_id })
    .where('(? BETWEEN start_date AND end_date) OR
            (? BETWEEN start_date AND end_date)', start_date, end_date)
end

def overlapping_approved_requests
  overlapping_requests.where(status: STATUSES.first)
end

def does_not_overlap_approved_request
  unless overlapping_approved_requests.empty?
    errors[:base] << 'Dates overlap. Bad. Not good.'
    return false
  end
  true
end

def approve!
  if status == 'PENDING'
    status = 'APPROVED'
    if self.save
      results = CatRentalRequest.where(cat_id: cat_id).where.not(id: id)
      results.each do |result|
        result.status = 'DENIED' unless result.does_not_overlap_approved_request
      end
    end
  end
end



end

W4D2/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery with: :exception
end

W4D2/app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController
  def index
    @cat_rental_requests = CatRentalRequest.all
    render :index


  end

  def show
    @cat_rental_request = CatRentalRequest.joins(:cat)
      .select('cat_rental_requests.*, cats.name')
      .where(id: params[:id]).first


    render :show
  end

  def new
    @cat_rental_request = CatRentalRequest.new
    render :new
  end

  def edit
    @cat_rental_request = CatRentalRequest.find_by(id: params[:id])
    render :edit
  end

  def create
    @cat_rental_request = CatRentalRequest.new(cat_rental_request_params)

    if @cat_rental_request.save
      redirect_to cat_rental_request_url(@cat_rental_request.id)
    else
      render :new
    end
  end

  def update
    @cat_rental_request = CatRentalRequest.find_by(id: params[:id])

    if @cat_rental_request.update(cat_rental_request_params)
      redirect_to cat_rental_request_url(@cat_rental_request.id)
    else
      render :edit
    end

  end

  private
  def cat_rental_request_params
    params.require(:cat_rental_request)
      .permit(:cat_id, :start_date, :end_date, :status)
  end

end

W4D2/app/controllers/cats_controller.rb
class CatsController < ApplicationController

  def index
    @cats = Cat.all
    render :index


  end

  def show
    @cat = Cat.left_outer_joins(:cat_rental_requests)
      .select('cats.*, cat_rental_requests.*')
      .where(cats: {id: params[:id]})
      .order('cat_rental_requests.start_date')

    render :show
  end

  def new
    @cat = Cat.new
    render :new
  end

  def edit
    @cat = Cat.find_by(id: params[:id])
    render :edit
  end

  def create
    @cat = Cat.new(cat_params)
    if @cat.save
      redirect_to cat_url(@cat.id)
    else
      render :new
    end
  end

  def update
    @cat = Cat.find_by(id: params[:id])

    if @cat.update(cat_params)
      redirect_to cat_url(@cat.id)
    else
      render :edit
    end

  end

  private
  def cat_params
    params.require(:cat).permit(:name, :color, :sex, :birth_date, :description)
  end
end

W4D2/app/views/cat_rental_requests/_form.html.erb
<% action_url = action == :edit ? cat_rental_request_url(cat_rental_request.id) : cat_rental_requests_url %>

<form action="<%=action_url%>" method="post">
<% if action == :edit %>
  <input type="hidden" name="_method" value="patch">
<% end %>

  <label for="cat_id">Cat: </label>
  <select id="cat_id" name="cat_rental_request[cat_id]">
      <option disabled selected>--Select Cat--</option>
    <% Cat.all.each do |cat| %>
      <option value="<%= cat.id %>"><%= cat.name %></option>
    <% end %>
  </select>

  <br>

  <label for="start_date">Start Date: </label>
    <input id="start_date" type="date" name="cat_rental_request[start_date]" value="<%= cat_rental_request.start_date %>">

  <br>

  <label for="end_date">End Date: </label>
    <input id="end_date" type="date" name="cat_rental_request[end_date]" value="<%= cat_rental_request.end_date %>">

  <br>

  <input type="submit" value="Add/Edit Cat Rental Request">

</form>

W4D2/app/views/cat_rental_requests/new.html.erb
<%= render 'form', action: :new, cat_rental_request: @cat_rental_request %>

W4D2/app/views/cat_rental_requests/show.html.erb
<table>
  <tr>
    <td>Cat Name: </td>
    <td> <%= @cat_rental_request.name %> </td>
  </tr>

  <tr>
    <td>Start Date: </td>
    <td> <%= @cat_rental_request.start_date %> </td>
  </tr>

  <tr>
    <td>End Date: </td>
    <td> <%= @cat_rental_request.end_date %> </td>
  </tr>

  <tr>
    <td>Status: </td>
    <td> <%= @cat_rental_request.status %> </td>
  </tr>


</table>